package ee.ponceau.steel;

import ee.ponceau.steel.util.Log;
import java.awt.image.BufferStrategy;
import javax.swing.JFrame;

/**
 *
 * @author Evan Verworn
 */
public class Window extends javax.swing.JFrame {
  public BufferStrategy buffer;
  
  /**
   * Creates new form Window
   */
  public Window() {
    super("Ponceau Steel");
    initComponents();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setVisible(true); 
    createBufferStrategy(2);
    buffer = getBufferStrategy();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 800, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Main.i.setWindow(new Window());
      }
    });
    
    if(args.length > 0) {
      switch(args[0]) {
        case "-debug": Log.STATE = Log.Level.LOG; break;
        case "-warning": Log.STATE = Log.Level.WARNING; break;
        case "-error": Log.STATE = Log.Level.ERROR; break;
        case "-fatal": Log.STATE = Log.Level.FATAL; break;
      }
    }
    
    Main.i.hold();
    Main.i.mainLoop();
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
